# Site settings
baseurl = "http://otselo.eu/"
defaultContentLanguage = "bg"
theme = "landing-page-hugo"

[params]
custom_css = ["css/local.css"]
googleAnalytics = "UA-108452990-1"

[[params.social]]
    title="email"
    icon="envelope-o"
    url="mailto:akodzhabashev@gmail.com"

[[params.social]]
    title="facebook"
    icon="facebook"
    url="https://www.facebook.com/otseloeu"

[[params.social]]
    title="phone"
    icon="phone"
    url="tel:+359-876-505-114"
    
[Languages]
[Languages.bg]
    title = "От село"
    description = "Устойчиво земеделие в мащаб"

[Languages.en]
    title = "From the village"
    description = "Sustainable agriculture at scale"

[taxonomies]
    tags = "tags"
    categories = "categories"
    

